services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-xlo!+$ob+pw5eynn$l75o$y4-sxpsy^o=j)*6r6$qh)n!af!$3
      - DJANGO_DEBUG=True
volumes:
  postgres_data:
